---
# Install and configure application code

- name: install supervisor
  apt: name=supervisor state=present

- name: install pip
  apt: name=python-pip state=present

- name: install virtualenv
  apt: name=python-virtualenv state=present

- name: install gunicorn
  pip: name=gunicorn

- name: install frijoles
  pip: name='https://github.com/Antojitos/frijoles/archive/{{ frijoles_version }}.tar.gz'

- name: create frijoles config directory
  file: path=/etc/frijoles state=directory mode=0755

- name: create configuration file for frijoles
  template: src=frijoles-config.py.j2 dest=/etc/frijoles/config.py

- name: create configuration file for supervisor
  template: src=supervisor-frijoles.conf.j2 dest=/etc/supervisor/conf.d/frijoles.conf
  notify: reload supervisor
