---
# Install and configure nginx

- name: install nginx server
  apt: name=nginx-full state=present

- name: create configuration file for frijoles site
  template: src=nginx-frijoles.site.j2 dest=/etc/nginx/sites-available/{{ frijoles_server_name }}
  notify: reload nginx

- name: enable frijoles site
  file: src=/etc/nginx/sites-available/{{ frijoles_server_name }} dest=/etc/nginx/sites-enabled/{{ frijoles_server_name }} state=link
  notify: reload nginx
